name: Laravel CI/CD Deploy

on:
  push:
    branches:
      - main  # deploy when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via Git Pull
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ${{ secrets.APP_PATH }}
            git fetch --all
            git reset --hard origin/main
            composer install --optimize-autoloader --no-dev
            npm install
            npm run build
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            sudo chown -R www-data:www-data ${{ secrets.APP_PATH }}
            sudo chmod -R 775 ${{ secrets.APP_PATH }}/storage ${{ secrets.APP_PATH }}/bootstrap/cache
            sudo systemctl restart apache2
